import { useState } from "react";
import PptxGenJS from "pptxgenjs";

// Import all 3 indexes
import { heroTemplates } from "../lib/templates/hero/index.jsx";
import { contentTemplates } from "../lib/templates/content/index.jsx";
import { closingTemplates } from "../lib/templates/closing/index.jsx";

// Merge all templates
const allTemplates = {
  ...heroTemplates,
  ...contentTemplates,
  ...closingTemplates,
};

// === GLOBAL LIGHT THEME ===
const globalTheme = {
  backgroundColor: "#FFFFFF",
  surfaceColor: "#F5F5F5",
  primaryTextColor: "#111111",
  secondaryTextColor: "#555555",
  accentColor: "#0EA5E9",
  fontFamily: "Calibri",
};

// === FULL 7-SLIDE AI AGENTS DECK ===
const fullDeck = [
  {
    category: "content",
    template: "content_title_bullets",
    templateDirection: "",
    title: "",
    description: "",
    keyPoints: [],
    prompt: "",
    data: {
      title: "AI‑Powered Healthcare Diagnostics",
      subtitle: "Transforming Diagnostic Care",
      bullets: [
        "AI as a catalyst for faster, more accurate diagnosis",
        "Targeting hospitals, investors, and tech teams",
        "Premium, technology‑focused narrative",
      ],
    },
    status: "pending",
    error: "",
  },
  {
    category: "content",
    template: "content_title_bullets",
    templateDirection: "",
    title: "",
    description: "",
    keyPoints: [],
    prompt: "",
    data: {
      title: "Current Challenges in Healthcare Diagnostics",
      subtitle: "Pain points limiting diagnostic quality",
      bullets: [
        "High false‑negative/positive rates",
        "Long turnaround times for imaging and labs",
        "Resource constraints and specialist shortages",
        "Rising costs and variable patient outcomes",
      ],
    },
    status: "pending",
    error: "",
  },
  {
    category: "content",
    template: "content_numbered_steps",
    templateDirection: "",
    title: "",
    description: "",
    keyPoints: [],
    prompt: "",
    data: {
      title: "AI Diagnostic Workflow Overview",
      steps: [
        {
          title: "Data acquisition",
          desc: "Imaging, EHR, wearables collected",
        },
        {
          title: "Pre‑processing & annotation",
          desc: "Clean, normalize, label data",
        },
        {
          title: "Model training & validation",
          desc: "Build and test AI models",
        },
        {
          title: "Real‑time inference & reporting",
          desc: "Deploy for decision support",
        },
      ],
    },
    status: "pending",
    error: "",
  },
  {
    category: "content",
    template: "content_numbered_steps",
    templateDirection: "",
    title: "",
    description: "",
    keyPoints: [],
    prompt: "",
    data: {
      title: "AI‑Driven Diagnostic Pipeline",
      steps: [
        {
          title: "Image capture → AI‑enhanced preprocessing",
          desc: "Raw scans are cleaned and optimized using AI algorithms.",
        },
        {
          title: "Automated feature extraction",
          desc: "AI models identify biomarkers and patterns from preprocessed images.",
        },
        {
          title: "Predictive analytics for disease risk",
          desc: "Risk scores are generated by analyzing extracted features.",
        },
        {
          title: "Clinician‑in‑the‑loop validation",
          desc: "Specialists review AI output before confirming the final diagnosis.",
        },
      ],
    },
    status: "pending",
    error: "",
  },
  {
    category: "content",
    template: "content_checklist",
    templateDirection: "",
    title: "",
    description: "",
    keyPoints: [],
    prompt: "",
    data: {
      title: "Key Benefits of AI Integration",
      subtitle: "Strategic advantages for stakeholders",
      items: [
        "Improved diagnostic accuracy",
        "Reduced time‑to‑treatment",
        "Lower operational costs",
        "Scalable decision support across specialties",
      ],
    },
    status: "pending",
    error: "",
  },
  {
    category: "content",
    template: "content_chart_placeholder",
    templateDirection: "",
    title: "",
    description: "",
    keyPoints: [],
    prompt: "",
    data: {
      title: "Accuracy Improvements & Metrics",
      chartType: "bar",
      seriesName: "AI vs Traditional",
      chartData: {
        labels: ["Sensitivity ↑", "False Positives ↓", "Reporting Time ↓"],
        values: [20, 20, 80],
      },
    },
    status: "pending",
    error: "",
  },
  {
    category: "content",
    template: "content_image_gallery",
    templateDirection: "",
    title: "",
    description: "",
    keyPoints: [],
    prompt: "",
    data: {
      title: "Real‑World Use Cases",
      images: [
        {
          url: "https://example.com/lung-nodule-detection.png",
          caption: "AI‑assisted lung nodule detection (Radiology)",
        },
        {
          url: "https://example.com/pathology-cancer-grading.png",
          caption: "Pathology slide analysis for cancer grading",
        },
        {
          url: "https://example.com/sepsis-prediction-icu.png",
          caption: "Predictive sepsis alerts in ICU settings",
        },
      ],
    },
    status: "pending",
    error: "",
  },
  {
    category: "content",
    template: "content_timeline_horizontal",
    templateDirection: "",
    title: "",
    description: "",
    keyPoints: [],
    prompt: "",
    data: {
      title: "Implementation Roadmap",
      items: [
        {
          title: "Phase 1",
          desc: "Data readiness & pilot study",
        },
        {
          title: "Phase 2",
          desc: "Model integration & staff training",
        },
        {
          title: "Phase 3",
          desc: "Scale‑up across departments",
        },
        {
          title: "Phase 4",
          desc: "Continuous monitoring & optimization",
        },
      ],
    },
    status: "pending",
    error: "",
  },
  {
    category: "content",
    template: "content_title_bullets",
    templateDirection: "",
    title: "",
    description: "",
    keyPoints: [],
    prompt: "",
    data: {
      title: "Future Scope & Innovation",
      subtitle: "Emerging trends and long‑term vision",
      bullets: [
        "Multimodal AI combining imaging, genomics, and wearables",
        "Federated learning for privacy‑preserving model improvement",
        "AI‑driven personalized treatment pathways",
        "Integration with tele‑health and remote diagnostics",
      ],
    },
    status: "pending",
    error: "",
  },
  {
    category: "content",
    template: "content_callout_box",
    templateDirection: "",
    title: "",
    description: "",
    keyPoints: [],
    prompt: "",
    data: {
      title: "Summary & Call to Action",
      message:
        "• AI delivers measurable accuracy and efficiency gains\n• Proven use cases demonstrate rapid ROI\n• Strategic roadmap ensures smooth adoption\n• Partner with us to lead the future of diagnostics",
      type: "success",
    },
    status: "pending",
    error: "",
  },
];

export default function FullDeckTester() {
  const [current, setCurrent] = useState(0);
  const slide = fullDeck[current];
  const Template = allTemplates[slide.template];

  const exportPPTX = async () => {
    const pptx = new PptxGenJS();
    pptx.layout = "LAYOUT_16x9";
    pptx.author = "AI Agents Deck";
    pptx.title = "AI Agents - Full Presentation";

    for (const s of fullDeck) {
      const tpl = allTemplates[s.template];
      const pptSlide = pptx.addSlide();
      if (tpl?.toPptx) {
        await tpl.toPptx(pptSlide, pptx, { ...s.data, theme: globalTheme });
      }
    }
    await pptx.writeFile({ fileName: "AI-Agents-Deck.pptx" });
  };

  return (
    <div className="h-screen flex flex-col bg-gray-50 text-gray-900">
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b bg-white shadow-sm">
        <h1 className="text-xl font-bold text-indigo-600">
          AI Agents Deck • {fullDeck.length} Slides
        </h1>
        <div className="flex gap-3 items-center">
          <button
            onClick={() => setCurrent(Math.max(0, current - 1))}
            disabled={current === 0}
            className="px-3 py-1.5 bg-gray-100 rounded-lg disabled:opacity-30 hover:bg-gray-200"
          >
            ← Prev
          </button>
          <span className="px-3 py-1.5 text-sm font-medium bg-indigo-50 text-indigo-700 rounded-lg">
            {current + 1} / {fullDeck.length}
          </span>
          <button
            onClick={() =>
              setCurrent(Math.min(fullDeck.length - 1, current + 1))
            }
            disabled={current === fullDeck.length - 1}
            className="px-3 py-1.5 bg-gray-100 rounded-lg disabled:opacity-30 hover:bg-gray-200"
          >
            Next →
          </button>
          <button
            onClick={exportPPTX}
            className="px-5 py-1.5 bg-indigo-600 text-white rounded-lg font-semibold hover:bg-indigo-700 shadow"
          >
            Export PPTX
          </button>
        </div>
      </div>

      {/* Preview */}
      <div className="flex-1 p-8 flex items-center justify-center bg-gradient-to-br from-gray-50 to-gray-100">
        <div className="w-full max-w-6xl aspect-video bg-white rounded-2xl shadow-2xl overflow-hidden border">
          {Template?.Preview ? (
            <Template.Preview data={{ ...slide.data, theme: globalTheme }} />
          ) : (
            <div className="w-full h-full flex items-center justify-center">
              No preview for {slide.template}
            </div>
          )}
        </div>
      </div>

      {/* Footer */}
      <div className="p-3 border-t bg-white text-xs text-gray-500 flex justify-between">
        <span>{slide.template}</span>
        <span>{slide.data.title}</span>
      </div>
    </div>
  );
}
